spring.application.name=EcopointsP2
spring.data.mongodb.uri=mongodb+srv://Rasmus Gravesen:<db_password>@brasil.sk6i5.mongodb.net/?appName=brasil
spring.data.mongodb.auto-index-creation=true
server.port=8080
